# Generated by Django 4.1.2 on 2023-11-10 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('games', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('loses', models.IntegerField()),
                ('win_percent', models.FloatField()),
                ('scored', models.FloatField()),
                ('missed', models.FloatField()),
                ('difference', models.FloatField()),
                ('home', models.CharField(max_length=100)),
                ('away', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='MatchesForPredictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tournament', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('name_team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions_team1', to='main.teams')),
                ('name_team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions_team2', to='main.teams')),
            ],
            options={
                'verbose_name': 'Прогноз на матч',
                'verbose_name_plural': 'Прогнозы на матчи',
            },
        ),
        migrations.CreateModel(
            name='All_matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tournament', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('name_team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_team1', to='main.teams')),
                ('name_team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_team2', to='main.teams')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
            },
        ),
    ]
