# Generated by Django 4.1.2 on 2023-11-10 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='All_matches',
            new_name='AllMatches',
        ),
    ]
