# Generated by Django 4.1.2 on 2023-11-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_all_matches_allmatches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmatches',
            name='name_team1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='allmatches',
            name='name_team2',
            field=models.CharField(max_length=100),
        ),
    ]
