# Generated by Django 4.1.2 on 2023-11-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_allmatches_name_team1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchesforpredictions',
            name='name_team1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matchesforpredictions',
            name='name_team2',
            field=models.CharField(max_length=100),
        ),
    ]
