# Generated by Django 4.1.2 on 2023-11-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_matchesforpredictions_name_team1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
