# Generated by Django 5.0 on 2023-12-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_teams_logo_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmatches',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
