# Generated by Django 4.2.8 on 2024-05-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_customteam_options_invitenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitenotification',
            name='notification_type',
            field=models.CharField(default='invite', max_length=100),
        ),
    ]
