# Generated by Django 4.2.8 on 2024-05-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_invitenotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitenotification',
            name='is_rejected',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Приглашение отклонено'),
        ),
        migrations.AlterField(
            model_name='invitenotification',
            name='is_invited',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Приглашение принято'),
        ),
    ]
