# Generated by Django 4.2.8 on 2024-05-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_invitenotification_is_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitenotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
