# Generated by Django 4.2.8 on 2024-05-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_teamfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamfiles',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
