# Generated by Django 4.2.8 on 2024-05-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_teamfiles_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamfiles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
