# Generated by Django 4.2.8 on 2024-05-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_subscriptions_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='promo_period',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='term',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
