# Generated by Django 4.2.8 on 2024-05-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_subscriptions_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='promo_period',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='term',
            field=models.IntegerField(default=30),
        ),
    ]
