# Generated by Django 4.2.8 on 2024-05-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_allmatches_time_matchesforpredictions_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='term_promo',
            field=models.IntegerField(default=2),
        ),
    ]
